### PR TITLE
Fix unicode conversion errors

### LINKED ISSUE #161: Intermittent argument errors during workspace cleanup
When I run `mix bootleg.build` I pretty regularly (but intermittently) get an error similar to the following during the workspace cleanup step.

```
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:standard_io, :unicode, [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[MY_IP_ADDRESS ] "] | "\e[0m"], "removed ‘_build/prod/rel/myapp/lib/db_connection-1.1.2/ebin/db_connection.app’"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[MY_IP_ADDRESS ] "] | "\e[0m"], "removed ‘_build/prod/rel/myapp/lib/db_connection-1.1.2/ebin/Elixir.DBConnection.Sojourn.Broker.beam’"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[MY_IP_ADDRESS ] "] | "\e[0m"], "removed ‘_build/prod/rel/myapp/lib/db_connection-1.1.2/ebin/Elixir.DBConnection.App.beam’"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[MY_IP_ADDRESS ] "] | "\e[0m"], "removed ‘_build/prod/rel/myapp/lib/db_connection-1.1.2/ebin/Elixir.DBConnection.Sojourn.Supervisor.beam’"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[MY_IP_ADDRESS ] "] | "\e[0m"], "removed ‘_build/prod/rel/myapp/lib/db_connection-1.1.2/ebin/Elixir.DBConnection.Poolboy.Worker.beam’"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[MY_IP_ADDRESS ] "] | "\e[0m"], "removed ‘_build/prod/rel/myapp/lib/db_connection-1.1.2/ebin/Elixir.DBConnection.Pool.beam’"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[MY_IP_ADDRESS ] "] | "\e[0m"], "removed ‘_build/prod/rel/myapp/lib/db_connection-1.1.2/ebin/Elixir.DBConnection.Query.beam’"] | "\e[0m"], 10])
    lib/bootleg/ssh.ex:90: Bootleg.SSH.capture/3
    lib/sshkit/ssh/channel.ex:224: SSHKit.SSH.Channel.loop/4
    lib/sshkit/ssh.ex:125: SSHKit.SSH.run/3
    lib/bootleg/ssh.ex:70: anonymous fn/2 in Bootleg.SSH.run/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:109: Bootleg.SSH.run!/2
    deps/bootleg/lib/bootleg/tasks/build.exs:31: anonymous fn/3 in Bootleg.DynamicTasks.Clean.execute/0
```

I haven't taken the time to look into this yet, so forgive me if this is a ticket for sshkit or some other dependency.

### LINKED ISSUE #169: ArgumentError during build step caused by `npm install`
Hi, thanks for the great tool!

I had this task in my `deploy.exs`:
```elixir
after_task :compile do
  remote :build do
    "[ -f package.json ] && npm install || true"
    "[ -f brunch-config.js ] && [ -d node_modules ] && ./node_modules/brunch/bin/brunch b -p || true"
    "[ -d deps/phoenix ] && mix phoenix.digest || true"
  end
end
```

Suddenly my builds start failing with this output:
```
...
[my-build-host] │ │ │ │ │ └── supports-color@2.0.0
[my-build-host] │ │ │ │ └─┬ supports-color@3.2.3
[my-build-host] │ │ │ │   └── has-flag@1.0.0
[my-build-host] │ │ │ ├── postcss-modules-extract-imports@1.1.0
[my-build-host] │ │ │ ├─┬ postcss-modules-local-by-default@1.2.0
[my-build-host] │ │ │ │ └─┬ css-selector-tokenizer@0.7.0
[my-build-host] │ │ │ │   ├── cssesc@0.1.0
[my-build-host] │ │ │ │   ├── fastparse@1.1.1
[my-build-host] │ │ │ │   └── regexpu-core@1.0.0
[my-build-host] │ │ │ ├── postcss-modules-scope@1.1.0
[my-build-host] │ │ │ └── postcss-modules-values@1.3.0
[my-build-host] │ │ ├─┬ generic-names@1.0.2
[my-build-host] │ │ │ └─┬ loader-utils@0.2.17
[my-build-host] │ │ │   ├── big.js@3.1.3
[my-build-host] │ │ │   └── emojis-list@2.1.0
[my-build-host] │ │ └── string-hash@1.1.3
[my-build-host] │ └─┬ progeny@0.9.0
[my-build-host] │   ├─┬ chalk@1.1.3
[my-build-host] │   │ ├── ansi-styles@2.2.1
[my-build-host] │   │ └── supports-color@2.0.0
[my-build-host] │   └─┬ fs-mode@1.0.1
[my-build-host] │     └─┬ cbify@1.0.0
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:standard_io, :unicode, [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[my-build-host] "] | "\e[0m"], "      ├─┬ cliui@2.1.0"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[my-build-host] "] | "\e[0m"], "      │ ├─┬ center-align@0.1.3"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[my-build-host] "] | "\e[0m"], "      │ │ ├─┬ align-text@0.1.4"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[my-build-host] "] | "\e[0m"], "      │ │ │ └── longest@1.0.1"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[my-build-host] "] | "\e[0m"], "      │ │ └── lazy-cache@1.0.4"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[my-build-host] "] | "\e[0m"], "      │ ├── right-align@0.1.3"], "\n"] | "\e[0m"] | "\e[1m"] | "\e[34m"], "[my-build-host] "] | "\e[0m"], "      │ └── wordwrap@0.0.2"] | "\e[0m"], 10])
    lib/bootleg/ssh.ex:90: Bootleg.SSH.capture/3
    lib/sshkit/ssh/channel.ex:224: SSHKit.SSH.Channel.loop/4
    lib/sshkit/ssh.ex:125: SSHKit.SSH.run/3
    lib/bootleg/ssh.ex:70: anonymous fn/2 in Bootleg.SSH.run/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:109: Bootleg.SSH.run!/2
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
```

I resolved this problem by replacing:
```
"[ -f package.json ] && npm install || true"
```
to
```
"[ -f package.json ] && npm install --silent > /dev/null || true"
```

### PR DESCRIPTION
**Pull request by rjanja**
* Use `IO.binwrite` instead of `IO.puts` to skip character conversion
* Remove dependency on Bunt
* Allow disabling of output coloring
* Closes #161, closes #169

### CODE REVIEW

File: lib/bootleg/ssh.ex [hunk 1]
```diff
@@ -45,6 +45,7 @@ defmodule Bootleg.SSH do
     |> List.wrap
     |> Enum.map(&ssh_host_options/1)
     |> SSHKit.context
+    |> SSHKit.env(%{"LANG" => "C", "LC_ALL" => "C"})
```
Comment (holetse) [inline lib/bootleg/ssh.ex]: This is making the test suite very unhappy. We should set the locale to utf8 if we are going to set it, as thats what elixir is expecting.

File: lib/ui.ex [hunk 2]
```diff
@@ -75,13 +75,14 @@ defmodule Bootleg.UI do
...
-      [:bright, :green]
+      [:reset, :bright, :green]
         ++ ["[" <> String.pad_trailing(host.name, 10) <> "] "]
         ++ [:reset, :yellow, "UPLOAD", " "]
         ++ [:reset, Path.relative_to_cwd(local_path)]
         ++ [:reset, :yellow, " -> "]
         ++ [:reset, Path.join(context.path, remote_path)]
-      |> Bunt.puts()
+      |> IO.ANSI.format(coloring_enabled())
+      |> IO.puts()
```
Comment (holetse) [inline lib/ui.ex]: Should this also be `IO.binwrite`? `puts_download` and `puts_send` have the same question.
